//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int Id { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioId { get; set; }
        public string Accion { get; set; }
        public string TipoAccion { get; set; }
        public string TablaAfectada { get; set; }
        public string Comentario { get; set; }
        public string Json1 { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
