//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventario
    {
        public int IdMovimientoInventario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int ProductoId { get; set; }
        public int DesdeUbicacionId { get; set; }
        public int HaciaUbicacionId { get; set; }
        public int Cantidad { get; set; }
        public int UsuarioId { get; set; }
        public string Observacion { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
